def GPA():
    print("Hello what class's grade would you like submit")
    print("1.Statistics")
    print("2.African american history")
    print("3.Choir")
    print("4.physic")
    print("5.Coding")
    select = int(input('Please Choose a class:'))
    if select == 1 :
          print("enter your statistics Grade:")
          print("week.1: " + str(input()))
          print("week.2: " + str(input()))
          print("week.3: " + str(input()))
          print("week.4: " + str(input()))
          print("week.5: " + str(input()))
          print("week.6: " + str(input()))
          print("week.7: " + str(input()))
          print("week.8: " + str(input()))
          print("week.9: " + str(input()))
          print("week.10: " + str(input()))
          print("week.11: " + str(input()))
          print("week.12: " + str(input()))
          print("week.13: " + str(input()))
          print("week.14:" + str(input()))
          print("week.15: " + str(input()))
          print("week.16: " + str(input()))
          print("week.17: " + str(input()))
          total =  int(input("enter your total grade:"))
          average = total / 17
          print("your average grade is: " + str(average))
    elif select == 2:
         print("enter your African american history Grade:")
         print("week.1: " + str(input()))
         print("week.2: " + str(input()))
         print("week.3: " + str(input()))
         print("week.4: " + str(input()))
         print("week.5: " + str(input()))
         print("week.6: " + str(input()))
         print("week.7: " + str(input()))
         print("week.8: " + str(input()))
         print("week.9: " + str(input()))
         print("week.10: " + str(input()))
         print("week.11: " + str(input()))
         print("week.12: " + str(input()))
         print("week.13: " + str(input()))
         print("week.14:" + str(input()))
         print("week.15: " + str(input()))
         print("week.16: " + str(input()))
         print("week.17: " + str(input()))
         total =  int(input("enter your total grade:"))
         average = total / 17
         print("your average grade is: " + str(average))
    elif select == 3:
         print("enter your Choir Grade:")
         print("week.1: " + str(input()))
         print("week.2: " + str(input()))
         print("week.3: " + str(input()))
         print("week.4: " + str(input()))
         print("week.5: " + str(input()))
         print("week.6: " + str(input()))
         print("week.7: " + str(input()))
         print("week.8: " + str(input()))
         print("week.9: " + str(input()))
         print("week.10: " + str(input()))
         print("week.11: " + str(input()))
         print("week.12: " + str(input()))
         print("week.13: " + str(input()))
         print("week.14:" + str(input()))
         print("week.15: " + str(input()))
         print("week.16: " + str(input()))
         print("week.17: " + str(input()))
         total =  int(input("enter your total grade:"))
         average = total / 17
         print("your average grade is: " + str(average))
    elif select == 4:
         print("enter your physic Grade:")
         print("week.1: " + str(input()))
         print("week.2: " + str(input()))
         print("week.3: " + str(input()))
         print("week.4: " + str(input()))
         print("week.5: " + str(input()))
         print("week.6: " + str(input()))
         print("week.7: " + str(input()))
         print("week.8: " + str(input()))
         print("week.9: " + str(input()))
         print("week.10: " + str(input()))
         print("week.11: " + str(input()))
         print("week.12: " + str(input()))
         print("week.13: " + str(input()))
         print("week.14:" + str(input()))
         print("week.15: " + str(input()))
         print("week.16: " + str(input()))
         print("week.17: " + str(input()))
         total =  int(input("enter your total grade:"))
         average = total / 17
         print("your average grade is: " + str(average))
    elif select == 5:
          print("enter your Coding Grade:")
          print("week.1: " + str(input()))
          print("week.2: " + str(input()))
          print("week.3: " + str(input()))
          print("week.4: " + str(input()))
          print("week.5: " + str(input()))
          print("week.6: " + str(input()))
          print("week.7: " + str(input()))
          print("week.8: " + str(input()))
          print("week.9: " + str(input()))
          print("week.10: " + str(input()))
          print("week.11: " + str(input()))
          print("week.12: " + str(input()))
          print("week.13: " + str(input()))
          print("week.14:" + str(input()))
          print("week.15: " + str(input()))
          print("week.16: " + str(input()))
          print("week.17: " + str(input()))
          total =  int(input("enter your total grade:"))
          average = total / 17
          print("your average grade is: " + str(average))
    else:
     print("sorry dont understand your selection")

GPA()