def GPA():
    print("Hello what class's grade would you like submit")
    print("1.Statistics")
    print("2.African american history")
    print("3.Choir")
    print("4.physic")
    print("5.Coding")
    select = int(input('Please Choose a class:'))
    if select == 1 :
          print("enter your statistics Grade:")
          wk1 = int(input("week.1:"))
          wk2 = int(input("week.2:"))
          wk3 = int(input("week.3:"))
          wk4 = int(input("week.4:"))
          wk5 = int(input("week.5:"))
          wk6 = int(input("week.6:"))
          wk7 = int(input("week.7:"))
          wk8 = int(input("week.8:"))
          wk9 = int(input("week.9:"))
          wk10 = int(input("week.10:"))
          wk11 = int(input("week.11:"))
          wk12 = int(input("week.12:"))
          wk13 = int(input("week.13:"))
          wk14 = int(input("week.14:"))
          wk15 = int(input("week.15:"))
          wk16 = int(input("week.16:"))
          wk17 = int(input("week.17:"))
          total =  wk1 + wk2 + wk3 + wk4 + wk5 + wk6 + wk7 + wk8 + wk9 + wk10 + wk11 + wk12 + wk13 + wk14 + wk15 + wk16 + wk17
          average = total / 17
          print("your average grade is: " + str(average))
    elif select == 2:
         print("enter your African american history Grade:")
         wk1 = int(input("week.1:"))
         wk2 = int(input("week.2:"))
         wk3 = int(input("week.3:"))
         wk4 = int(input("week.4:"))
         wk5 = int(input("week.5:"))
         wk6 = int(input("week.6:"))
         wk7 = int(input("week.7:"))          
         wk8 = int(input("week.8:"))
         wk9 = int(input("week.9:"))
         wk10 = int(input("week.10:"))
         wk11 = int(input("week.11:"))
         wk12 = int(input("week.12:"))
         wk13 = int(input("week.13:"))
         wk14 = int(input("week.14:"))
         wk15 = int(input("week.15:"))
         wk16 = int(input("week.16:"))
         wk17 = int(input("week.17:"))
         total =  wk1 + wk2 + wk3 + wk4 + wk5 + wk6 + wk7 + wk8 + wk9 + wk10 + wk11 + wk12 + wk13 + wk14 + wk15 + wk16 + wk17
         average = total / 17
         print("your average grade is: " + str(average))
    elif select == 3:
         print("enter your Choir Grade:")
         wk1 = int(input("week.1:"))
         wk2 = int(input("week.2:"))
         wk3 = int(input("week.3:"))
         wk4 = int(input("week.4:"))
         wk5 = int(input("week.5:"))
         wk6 = int(input("week.6:"))
         wk7 = int(input("week.7:"))          
         wk8 = int(input("week.8:"))
         wk9 = int(input("week.9:"))
         wk10 = int(input("week.10:"))
         wk11 = int(input("week.11:"))
         wk12 = int(input("week.12:"))
         wk13 = int(input("week.13:"))
         wk14 = int(input("week.14:"))
         wk15 = int(input("week.15:"))
         wk16 = int(input("week.16:"))
         wk17 = int(input("week.17:"))
         average = total / 17
         print("your average grade is: " + str(average))
    elif select == 4:
         print("enter your physic Grade:")
         wk1 = int(input("week.1:"))
         wk2 = int(input("week.2:"))
         wk3 = int(input("week.3:"))
         wk4 = int(input("week.4:"))
         wk5 = int(input("week.5:"))
         wk6 = int(input("week.6:"))
         wk7 = int(input("week.7:"))          
         wk8 = int(input("week.8:"))
         wk9 = int(input("week.9:"))
         wk10 = int(input("week.10:"))
         wk11 = int(input("week.11:"))
         wk12 = int(input("week.12:"))
         wk13 = int(input("week.13:"))
         wk14 = int(input("week.14:"))
         wk15 = int(input("week.15:"))
         wk16 = int(input("week.16:"))
         wk17 = int(input("week.17:"))
         average = total / 17
         print("your average grade is: " + str(average))
    elif select == 5:
          print("enter your Coding Grade:")
          wk1 = int(input("week.1:"))
          wk2 = int(input("week.2:"))
          wk3 = int(input("week.3:"))
          wk4 = int(input("week.4:"))
          wk5 = int(input("week.5:"))
          wk6 = int(input("week.6:"))
          wk7 = int(input("week.7:"))          
          wk8 = int(input("week.8:"))
          wk9 = int(input("week.9:"))
          wk10 = int(input("week.10:"))
          wk11 = int(input("week.11:"))
          wk12 = int(input("week.12:"))
          wk13 = int(input("week.13:"))
          wk14 = int(input("week.14:"))
          wk15 = int(input("week.15:"))
          wk16 = int(input("week.16:"))
          wk17 = int(input("week.17:"))
          total =  wk1 + wk2 + wk3 + wk4 + wk5 + wk6 + wk7 + wk8 + wk9 + wk10 + wk11 + wk12 + wk13 + wk14 + wk15 + wk16 + wk17
          average = total / 17
          print("your average grade is: " + str(average))
    else: 
          print("sorry dont understand your selection")

GPA()